### ISSUE TITLE
boolean column can not be null.

### ISSUE THREAD

**Issue by rambai** [szczurmys/ignite-cassandra-store#3]
Hello, now I have an issue that cache could not start if persistence table have null's in boolean type field:
Caused by: java.lang.IllegalArgumentException: Can't cast null value from Cassandra table column 'tag_boolean_value' to boolean value used in domain object model
	at com.github.szczurmys.ignite.cache.store.cassandra.handler.PrimitiveBooleanTypeHandler.toJavaType(PrimitiveBooleanTypeHandler.java:47)
	at com.github.szczurmys.ignite.cache.store.cassandra.handler.PrimitiveBooleanTypeHandler.toJavaType(PrimitiveBooleanTypeHandler.java:26)
	at com.github.szczurmys.ignite.cache.store.cassandra.persistence.PojoField.setValueFromRow(PojoField.java:224)
	at com.github.szczurmys.ignite.cache.store.cassandra.persistence.PersistenceController.buildObject(PersistenceController.java:406)
	at com.github.szczurmys.ignite.cache.store.cassandra.persistence.PersistenceController.buildValueObject(PersistenceController.java:228)
	at com.github.szczurmys.ignite.cache.store.cassandra.session.LoadCacheCustomQueryWorker$1.process(LoadCacheCustomQueryWorker.java:107)
	... 7 more

**Comment by szczurmys** [comment]
I added a fix, similar to https://github.com/apache/ignite/commit/1858acff7646c7aad61e8bbcd84039bb2d5a2db3 

so, if you want use null, you have to use non primitive type, `java.lang.Boolean` instead of `boolean`.

**Comment by szczurmys** [comment]
or, you can implement your own TypeHandler with different behaviour, where null will be false :)

**Comment by rambai** [comment]
Thank for replay, could you confirm that if I use java.lang.Boolean it give false if null? I need to get null if there is null in the cell.

**Comment by szczurmys** [comment]
No. If you use java.lang.Boolean, then it gives you null if null :). 

https://github.com/szczurmys/ignite-cassandra-store/blob/master/src/main/java/com/github/szczurmys/ignite/cache/store/cassandra/handler/BooleanTypeHandler.java
